# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos_convertidor_de_archivos import ConvertidorDeArchivos_pb2 as protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2


class ConvertidorDeCancionesStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertirCancionAMp3 = channel.stream_stream(
                '/convertidor_de_archivos.ConvertidorDeCanciones/ConvertirCancionAMp3',
                request_serializer=protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.SolicitudConvertirCancionMp3.SerializeToString,
                response_deserializer=protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.RespuestaCancionesConvertidas.FromString,
                )


class ConvertidorDeCancionesServicer(object):
    """Missing associated documentation comment in .proto file"""

    def ConvertirCancionAMp3(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConvertidorDeCancionesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertirCancionAMp3': grpc.stream_stream_rpc_method_handler(
                    servicer.ConvertirCancionAMp3,
                    request_deserializer=protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.SolicitudConvertirCancionMp3.FromString,
                    response_serializer=protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.RespuestaCancionesConvertidas.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'convertidor_de_archivos.ConvertidorDeCanciones', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConvertidorDeCanciones(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def ConvertirCancionAMp3(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/convertidor_de_archivos.ConvertidorDeCanciones/ConvertirCancionAMp3',
            protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.SolicitudConvertirCancionMp3.SerializeToString,
            protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.RespuestaCancionesConvertidas.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
