"""Migracion inicial

Revision ID: 0ceecd231add
Revises: 
Create Date: 2020-06-04 04:05:39.743250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ceecd231add'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creador_de_contenido',
    sa.Column('id_creador_de_contenido', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('biografia', sa.String(length=500), nullable=True),
    sa.Column('es_grupo', sa.Boolean(), nullable=False),
    sa.Column('usuario_nombre_usuario', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_creador_de_contenido')
    )
    op.create_index(op.f('ix_creador_de_contenido_usuario_nombre_usuario'), 'creador_de_contenido', ['usuario_nombre_usuario'], unique=False)
    op.create_table('disquera',
    sa.Column('id_disquera', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('es_empresa', sa.Boolean(), nullable=False),
    sa.Column('nombre_usuario_creador', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_disquera')
    )
    op.create_table('genero',
    sa.Column('id_genero', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genero', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_genero')
    )
    op.create_table('usuario',
    sa.Column('nombre_usuario', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('contrasena', sa.String(length=80), nullable=False),
    sa.Column('tipo_usuario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nombre_usuario')
    )
    op.create_table('artista',
    sa.Column('id_artista', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('creador_de_contenido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creador_de_contenido_id'], ['creador_de_contenido.id_creador_de_contenido'], ),
    sa.PrimaryKeyConstraint('id_artista')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artista')
    op.drop_table('usuario')
    op.drop_table('genero')
    op.drop_table('disquera')
    op.drop_index(op.f('ix_creador_de_contenido_usuario_nombre_usuario'), table_name='creador_de_contenido')
    op.drop_table('creador_de_contenido')
    # ### end Alembic commands ###
