"""Modelo album

Revision ID: 8383eb7afc27
Revises: 0ceecd231add
Create Date: 2020-06-05 00:46:32.712105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8383eb7afc27'
down_revision = '0ceecd231add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id_album', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('anio_lanzamiento', sa.String(length=4), nullable=False),
    sa.Column('duracion_total_segundos', sa.Float(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creador_de_contenido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creador_de_contenido_id'], ['creador_de_contenido.id_creador_de_contenido'], ),
    sa.PrimaryKeyConstraint('id_album')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album')
    # ### end Alembic commands ###
