"""Modelo album

Revision ID: f4a79e35f1a8
Revises: 
Create Date: 2020-06-06 23:55:28.671818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a79e35f1a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creador_de_contenido',
    sa.Column('id_creador_de_contenido', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('biografia', sa.String(length=500), nullable=True),
    sa.Column('es_grupo', sa.Boolean(), nullable=False),
    sa.Column('usuario_nombre_usuario', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_creador_de_contenido')
    )
    op.create_index(op.f('ix_creador_de_contenido_usuario_nombre_usuario'), 'creador_de_contenido', ['usuario_nombre_usuario'], unique=False)
    op.create_table('disquera',
    sa.Column('id_disquera', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('es_empresa', sa.Boolean(), nullable=False),
    sa.Column('nombre_usuario_creador', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_disquera')
    )
    op.create_table('genero',
    sa.Column('id_genero', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genero', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_genero')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('contrasena', sa.String(length=80), nullable=False),
    sa.Column('tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_index(op.f('ix_usuario_nombre_usuario'), 'usuario', ['nombre_usuario'], unique=True)
    op.create_table('album',
    sa.Column('id_album', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('anio_lanzamiento', sa.String(length=4), nullable=False),
    sa.Column('duracion_total_segundos', sa.Float(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creador_de_contenido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creador_de_contenido_id'], ['creador_de_contenido.id_creador_de_contenido'], ),
    sa.PrimaryKeyConstraint('id_album')
    )
    op.create_table('artista',
    sa.Column('id_artista', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('creador_de_contenido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creador_de_contenido_id'], ['creador_de_contenido.id_creador_de_contenido'], ),
    sa.PrimaryKeyConstraint('id_artista')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artista')
    op.drop_table('album')
    op.drop_index(op.f('ix_usuario_nombre_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('genero')
    op.drop_table('disquera')
    op.drop_index(op.f('ix_creador_de_contenido_usuario_nombre_usuario'), table_name='creador_de_contenido')
    op.drop_table('creador_de_contenido')
    # ### end Alembic commands ###
