"""Se agrego el modelo lista de reproduccion

Revision ID: 1f0f7a0fbe6e
Revises: 3f899d41c646
Create Date: 2020-06-13 14:45:34.632296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0f7a0fbe6e'
down_revision = '3f899d41c646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista_de_reproduccion',
    sa.Column('id_lista_de_reproduccion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_lista_de_reproduccion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lista_de_reproduccion')
    # ### end Alembic commands ###
