"""Se agrego el campo duracion_total

Revision ID: 342a51f57d5b
Revises: 1f0f7a0fbe6e
Create Date: 2020-06-14 02:06:40.127617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342a51f57d5b'
down_revision = '1f0f7a0fbe6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lista_de_reproduccion', sa.Column('duracion_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lista_de_reproduccion', 'duracion_total')
    # ### end Alembic commands ###
