"""Se agrego el modelo calificaicon

Revision ID: 3f899d41c646
Revises: 
Create Date: 2020-06-11 21:58:32.452759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f899d41c646'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancion',
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('duracion_en_segundos', sa.Float(), nullable=True),
    sa.Column('cantidad_de_reproducciones', sa.Integer(), nullable=True),
    sa.Column('calificacion_promedio', sa.Float(), nullable=True),
    sa.Column('eliminada', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_cancion')
    )
    op.create_table('creador_de_contenido',
    sa.Column('id_creador_de_contenido', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('biografia', sa.String(length=500), nullable=True),
    sa.Column('es_grupo', sa.Boolean(), nullable=False),
    sa.Column('usuario_id_usuario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_creador_de_contenido')
    )
    op.create_index(op.f('ix_creador_de_contenido_usuario_id_usuario'), 'creador_de_contenido', ['usuario_id_usuario'], unique=False)
    op.create_table('disquera',
    sa.Column('id_disquera', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('es_empresa', sa.Boolean(), nullable=False),
    sa.Column('nombre_usuario_creador', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_disquera')
    )
    op.create_table('genero',
    sa.Column('id_genero', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genero', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_genero')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('contrasena', sa.String(length=80), nullable=False),
    sa.Column('tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_index(op.f('ix_usuario_nombre_usuario'), 'usuario', ['nombre_usuario'], unique=True)
    op.create_table('album',
    sa.Column('id_album', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('anio_lanzamiento', sa.String(length=4), nullable=False),
    sa.Column('duracion_total_segundos', sa.Float(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creador_de_contenido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creador_de_contenido_id'], ['creador_de_contenido.id_creador_de_contenido'], ),
    sa.PrimaryKeyConstraint('id_album')
    )
    op.create_table('artistas_generos',
    sa.Column('id_creador_de_contenido', sa.Integer(), nullable=False),
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_creador_de_contenido'], ['creador_de_contenido.id_creador_de_contenido'], ),
    sa.ForeignKeyConstraint(['id_genero'], ['genero.id_genero'], ),
    sa.PrimaryKeyConstraint('id_creador_de_contenido', 'id_genero')
    )
    op.create_table('calificacion',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.Column('calificacion_estrellas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_cancion')
    )
    op.create_table('creadores_canciones',
    sa.Column('id_creador_de_contenido', sa.Integer(), nullable=False),
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_creador_de_contenido'], ['creador_de_contenido.id_creador_de_contenido'], ),
    sa.PrimaryKeyConstraint('id_creador_de_contenido', 'id_cancion')
    )
    op.create_table('generos_de_la_cancion',
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_genero'], ['genero.id_genero'], ),
    sa.PrimaryKeyConstraint('id_cancion', 'id_genero')
    )
    op.create_table('albumes_de_la_cancion',
    sa.Column('id_album', sa.Integer(), nullable=False),
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_album'], ['album.id_album'], ),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.PrimaryKeyConstraint('id_album', 'id_cancion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albumes_de_la_cancion')
    op.drop_table('generos_de_la_cancion')
    op.drop_table('creadores_canciones')
    op.drop_table('calificacion')
    op.drop_table('artistas_generos')
    op.drop_table('album')
    op.drop_index(op.f('ix_usuario_nombre_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('genero')
    op.drop_table('disquera')
    op.drop_index(op.f('ix_creador_de_contenido_usuario_id_usuario'), table_name='creador_de_contenido')
    op.drop_table('creador_de_contenido')
    op.drop_table('cancion')
    # ### end Alembic commands ###
