"""Se agrego la bilbioteca personal

Revision ID: 9029822ead15
Revises: cdf9df5fb2d7
Create Date: 2020-06-17 17:24:38.454397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9029822ead15'
down_revision = 'cdf9df5fb2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancion_personal',
    sa.Column('id_cancion_personal', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('artistas', sa.String(length=100), nullable=False),
    sa.Column('duracion_en_segundos', sa.Integer(), nullable=True),
    sa.Column('album', sa.String(length=70), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cancion_personal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancion_personal')
    # ### end Alembic commands ###
