"""Se agrego la relacion de lista a canciones

Revision ID: fc58d4591af5
Revises: 342a51f57d5b
Create Date: 2020-06-14 03:22:29.950416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc58d4591af5'
down_revision = '342a51f57d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canciones_de_listas_reproduccion',
    sa.Column('id_lista_de_reproduccion', sa.Integer(), nullable=False),
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_lista_de_reproduccion'], ['lista_de_reproduccion.id_lista_de_reproduccion'], ),
    sa.PrimaryKeyConstraint('id_lista_de_reproduccion', 'id_cancion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('canciones_de_listas_reproduccion')
    # ### end Alembic commands ###
