# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/ConvertidorDeArchivos.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/ConvertidorDeArchivos.proto',
  package='convertidor_de_archivos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\"protos/ConvertidorDeArchivos.proto\x12\x17\x63onvertidor_de_archivos\".\n\x0c\x45rrorGeneral\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"K\n\x12InformacionArchivo\x12\x11\n\tidCancion\x18\x01 \x01(\x03\x12\x11\n\textension\x18\x02 \x01(\t\x12\x0f\n\x07hash256\x18\x03 \x01(\t\"\x15\n\x05\x43hunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x98\x01\n\x1cSolicitudConvertirCancionMp3\x12G\n\x12informacionArchivo\x18\x01 \x01(\x0b\x32+.convertidor_de_archivos.InformacionArchivo\x12/\n\x07paquete\x18\x02 \x01(\x0b\x32\x1e.convertidor_de_archivos.Chunk\"\x96\x01\n\x1aRespuestaCancionConvertida\x12G\n\x12informacionArchivo\x18\x01 \x01(\x0b\x32+.convertidor_de_archivos.InformacionArchivo\x12/\n\x07paquete\x18\x02 \x01(\x0b\x32\x1e.convertidor_de_archivos.Chunk\"\xc9\x02\n\x1dRespuestaCancionesConvertidas\x12O\n\x12\x63\x61ncionCalidadAlta\x18\x01 \x01(\x0b\x32\x33.convertidor_de_archivos.RespuestaCancionConvertida\x12P\n\x13\x63\x61ncionCalidadMedia\x18\x02 \x01(\x0b\x32\x33.convertidor_de_archivos.RespuestaCancionConvertida\x12O\n\x12\x63\x61ncionCalidadBaja\x18\x03 \x01(\x0b\x32\x33.convertidor_de_archivos.RespuestaCancionConvertida\x12\x34\n\x05\x65rror\x18\x04 \x01(\x0b\x32%.convertidor_de_archivos.ErrorGeneral*/\n\x0e\x43\x61lidadCancion\x12\x08\n\x04\x41LTA\x10\x00\x12\t\n\x05MEDIA\x10\x01\x12\x08\n\x04\x42\x41JA\x10\x02\x32\xa6\x01\n\x16\x43onvertidorDeCanciones\x12\x8b\x01\n\x14\x43onvertirCancionAMp3\x12\x35.convertidor_de_archivos.SolicitudConvertirCancionMp3\x1a\x36.convertidor_de_archivos.RespuestaCancionesConvertidas\"\x00(\x01\x30\x01\x62\x06proto3'
)

_CALIDADCANCION = _descriptor.EnumDescriptor(
  name='CalidadCancion',
  full_name='convertidor_de_archivos.CalidadCancion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALTA', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIA', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAJA', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=851,
  serialized_end=898,
)
_sym_db.RegisterEnumDescriptor(_CALIDADCANCION)

CalidadCancion = enum_type_wrapper.EnumTypeWrapper(_CALIDADCANCION)
ALTA = 0
MEDIA = 1
BAJA = 2



_ERRORGENERAL = _descriptor.Descriptor(
  name='ErrorGeneral',
  full_name='convertidor_de_archivos.ErrorGeneral',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='convertidor_de_archivos.ErrorGeneral.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='convertidor_de_archivos.ErrorGeneral.mensaje', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=109,
)


_INFORMACIONARCHIVO = _descriptor.Descriptor(
  name='InformacionArchivo',
  full_name='convertidor_de_archivos.InformacionArchivo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idCancion', full_name='convertidor_de_archivos.InformacionArchivo.idCancion', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extension', full_name='convertidor_de_archivos.InformacionArchivo.extension', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash256', full_name='convertidor_de_archivos.InformacionArchivo.hash256', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=186,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='convertidor_de_archivos.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='convertidor_de_archivos.Chunk.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=209,
)


_SOLICITUDCONVERTIRCANCIONMP3 = _descriptor.Descriptor(
  name='SolicitudConvertirCancionMp3',
  full_name='convertidor_de_archivos.SolicitudConvertirCancionMp3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='informacionArchivo', full_name='convertidor_de_archivos.SolicitudConvertirCancionMp3.informacionArchivo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paquete', full_name='convertidor_de_archivos.SolicitudConvertirCancionMp3.paquete', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=364,
)


_RESPUESTACANCIONCONVERTIDA = _descriptor.Descriptor(
  name='RespuestaCancionConvertida',
  full_name='convertidor_de_archivos.RespuestaCancionConvertida',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='informacionArchivo', full_name='convertidor_de_archivos.RespuestaCancionConvertida.informacionArchivo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paquete', full_name='convertidor_de_archivos.RespuestaCancionConvertida.paquete', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=517,
)


_RESPUESTACANCIONESCONVERTIDAS = _descriptor.Descriptor(
  name='RespuestaCancionesConvertidas',
  full_name='convertidor_de_archivos.RespuestaCancionesConvertidas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cancionCalidadAlta', full_name='convertidor_de_archivos.RespuestaCancionesConvertidas.cancionCalidadAlta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cancionCalidadMedia', full_name='convertidor_de_archivos.RespuestaCancionesConvertidas.cancionCalidadMedia', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cancionCalidadBaja', full_name='convertidor_de_archivos.RespuestaCancionesConvertidas.cancionCalidadBaja', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='convertidor_de_archivos.RespuestaCancionesConvertidas.error', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=849,
)

_SOLICITUDCONVERTIRCANCIONMP3.fields_by_name['informacionArchivo'].message_type = _INFORMACIONARCHIVO
_SOLICITUDCONVERTIRCANCIONMP3.fields_by_name['paquete'].message_type = _CHUNK
_RESPUESTACANCIONCONVERTIDA.fields_by_name['informacionArchivo'].message_type = _INFORMACIONARCHIVO
_RESPUESTACANCIONCONVERTIDA.fields_by_name['paquete'].message_type = _CHUNK
_RESPUESTACANCIONESCONVERTIDAS.fields_by_name['cancionCalidadAlta'].message_type = _RESPUESTACANCIONCONVERTIDA
_RESPUESTACANCIONESCONVERTIDAS.fields_by_name['cancionCalidadMedia'].message_type = _RESPUESTACANCIONCONVERTIDA
_RESPUESTACANCIONESCONVERTIDAS.fields_by_name['cancionCalidadBaja'].message_type = _RESPUESTACANCIONCONVERTIDA
_RESPUESTACANCIONESCONVERTIDAS.fields_by_name['error'].message_type = _ERRORGENERAL
DESCRIPTOR.message_types_by_name['ErrorGeneral'] = _ERRORGENERAL
DESCRIPTOR.message_types_by_name['InformacionArchivo'] = _INFORMACIONARCHIVO
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['SolicitudConvertirCancionMp3'] = _SOLICITUDCONVERTIRCANCIONMP3
DESCRIPTOR.message_types_by_name['RespuestaCancionConvertida'] = _RESPUESTACANCIONCONVERTIDA
DESCRIPTOR.message_types_by_name['RespuestaCancionesConvertidas'] = _RESPUESTACANCIONESCONVERTIDAS
DESCRIPTOR.enum_types_by_name['CalidadCancion'] = _CALIDADCANCION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrorGeneral = _reflection.GeneratedProtocolMessageType('ErrorGeneral', (_message.Message,), {
  'DESCRIPTOR' : _ERRORGENERAL,
  '__module__' : 'protos.ConvertidorDeArchivos_pb2'
  # @@protoc_insertion_point(class_scope:convertidor_de_archivos.ErrorGeneral)
  })
_sym_db.RegisterMessage(ErrorGeneral)

InformacionArchivo = _reflection.GeneratedProtocolMessageType('InformacionArchivo', (_message.Message,), {
  'DESCRIPTOR' : _INFORMACIONARCHIVO,
  '__module__' : 'protos.ConvertidorDeArchivos_pb2'
  # @@protoc_insertion_point(class_scope:convertidor_de_archivos.InformacionArchivo)
  })
_sym_db.RegisterMessage(InformacionArchivo)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'protos.ConvertidorDeArchivos_pb2'
  # @@protoc_insertion_point(class_scope:convertidor_de_archivos.Chunk)
  })
_sym_db.RegisterMessage(Chunk)

SolicitudConvertirCancionMp3 = _reflection.GeneratedProtocolMessageType('SolicitudConvertirCancionMp3', (_message.Message,), {
  'DESCRIPTOR' : _SOLICITUDCONVERTIRCANCIONMP3,
  '__module__' : 'protos.ConvertidorDeArchivos_pb2'
  # @@protoc_insertion_point(class_scope:convertidor_de_archivos.SolicitudConvertirCancionMp3)
  })
_sym_db.RegisterMessage(SolicitudConvertirCancionMp3)

RespuestaCancionConvertida = _reflection.GeneratedProtocolMessageType('RespuestaCancionConvertida', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTACANCIONCONVERTIDA,
  '__module__' : 'protos.ConvertidorDeArchivos_pb2'
  # @@protoc_insertion_point(class_scope:convertidor_de_archivos.RespuestaCancionConvertida)
  })
_sym_db.RegisterMessage(RespuestaCancionConvertida)

RespuestaCancionesConvertidas = _reflection.GeneratedProtocolMessageType('RespuestaCancionesConvertidas', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTACANCIONESCONVERTIDAS,
  '__module__' : 'protos.ConvertidorDeArchivos_pb2'
  # @@protoc_insertion_point(class_scope:convertidor_de_archivos.RespuestaCancionesConvertidas)
  })
_sym_db.RegisterMessage(RespuestaCancionesConvertidas)



_CONVERTIDORDECANCIONES = _descriptor.ServiceDescriptor(
  name='ConvertidorDeCanciones',
  full_name='convertidor_de_archivos.ConvertidorDeCanciones',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=901,
  serialized_end=1067,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConvertirCancionAMp3',
    full_name='convertidor_de_archivos.ConvertidorDeCanciones.ConvertirCancionAMp3',
    index=0,
    containing_service=None,
    input_type=_SOLICITUDCONVERTIRCANCIONMP3,
    output_type=_RESPUESTACANCIONESCONVERTIDAS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONVERTIDORDECANCIONES)

DESCRIPTOR.services_by_name['ConvertidorDeCanciones'] = _CONVERTIDORDECANCIONES

# @@protoc_insertion_point(module_scope)
