# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import ManejadorDeArchivos_pb2 as protos_dot_ManejadorDeArchivos__pb2


class CancionesStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubirCancionPersonal = channel.stream_unary(
                '/manejador_de_archivos.Canciones/SubirCancionPersonal',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                )
        self.SubirCancion = channel.stream_unary(
                '/manejador_de_archivos.Canciones/SubirCancion',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                )
        self.ObtenerCancion = channel.unary_stream(
                '/manejador_de_archivos.Canciones/ObtenerCancion',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.FromString,
                )
        self.ObtenerCancionPersonal = channel.unary_stream(
                '/manejador_de_archivos.Canciones/ObtenerCancionPersonal',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.FromString,
                )


class CancionesServicer(object):
    """Missing associated documentation comment in .proto file"""

    def SubirCancionPersonal(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubirCancion(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCancion(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCancionPersonal(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CancionesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubirCancionPersonal': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirCancionPersonal,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'SubirCancion': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirCancion,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'ObtenerCancion': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerCancion,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.SerializeToString,
            ),
            'ObtenerCancionPersonal': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerCancionPersonal,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manejador_de_archivos.Canciones', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Canciones(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def SubirCancionPersonal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/manejador_de_archivos.Canciones/SubirCancionPersonal',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubirCancion(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/manejador_de_archivos.Canciones/SubirCancion',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtenerCancion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/manejador_de_archivos.Canciones/ObtenerCancion',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtenerCancionPersonal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/manejador_de_archivos.Canciones/ObtenerCancionPersonal',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class PortadasStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubirPortadaAlbum = channel.stream_unary(
                '/manejador_de_archivos.Portadas/SubirPortadaAlbum',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                )
        self.SubirPortadaCreadorDeContenido = channel.stream_unary(
                '/manejador_de_archivos.Portadas/SubirPortadaCreadorDeContenido',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                )
        self.SubirPortadaUsuario = channel.stream_unary(
                '/manejador_de_archivos.Portadas/SubirPortadaUsuario',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                )
        self.SubirPortadaListaDeReproduccion = channel.stream_unary(
                '/manejador_de_archivos.Portadas/SubirPortadaListaDeReproduccion',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                )
        self.ObtenerPortadaAlbum = channel.unary_stream(
                '/manejador_de_archivos.Portadas/ObtenerPortadaAlbum',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
                )
        self.ObtenerPortadaCreadorDeContenido = channel.unary_stream(
                '/manejador_de_archivos.Portadas/ObtenerPortadaCreadorDeContenido',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
                )
        self.ObtenerPortadaUsuario = channel.unary_stream(
                '/manejador_de_archivos.Portadas/ObtenerPortadaUsuario',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
                )
        self.ObtenerPortadaListaDeReproduccion = channel.unary_stream(
                '/manejador_de_archivos.Portadas/ObtenerPortadaListaDeReproduccion',
                request_serializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
                response_deserializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
                )


class PortadasServicer(object):
    """Missing associated documentation comment in .proto file"""

    def SubirPortadaAlbum(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubirPortadaCreadorDeContenido(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubirPortadaUsuario(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubirPortadaListaDeReproduccion(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerPortadaAlbum(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerPortadaCreadorDeContenido(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerPortadaUsuario(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerPortadaListaDeReproduccion(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortadasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubirPortadaAlbum': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirPortadaAlbum,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'SubirPortadaCreadorDeContenido': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirPortadaCreadorDeContenido,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'SubirPortadaUsuario': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirPortadaUsuario,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'SubirPortadaListaDeReproduccion': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirPortadaListaDeReproduccion,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'ObtenerPortadaAlbum': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerPortadaAlbum,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.SerializeToString,
            ),
            'ObtenerPortadaCreadorDeContenido': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerPortadaCreadorDeContenido,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.SerializeToString,
            ),
            'ObtenerPortadaUsuario': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerPortadaUsuario,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.SerializeToString,
            ),
            'ObtenerPortadaListaDeReproduccion': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerPortadaListaDeReproduccion,
                    request_deserializer=protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.FromString,
                    response_serializer=protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manejador_de_archivos.Portadas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Portadas(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def SubirPortadaAlbum(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/manejador_de_archivos.Portadas/SubirPortadaAlbum',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubirPortadaCreadorDeContenido(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/manejador_de_archivos.Portadas/SubirPortadaCreadorDeContenido',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubirPortadaUsuario(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/manejador_de_archivos.Portadas/SubirPortadaUsuario',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubirPortadaListaDeReproduccion(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/manejador_de_archivos.Portadas/SubirPortadaListaDeReproduccion',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtenerPortadaAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/manejador_de_archivos.Portadas/ObtenerPortadaAlbum',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtenerPortadaCreadorDeContenido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/manejador_de_archivos.Portadas/ObtenerPortadaCreadorDeContenido',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtenerPortadaUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/manejador_de_archivos.Portadas/ObtenerPortadaUsuario',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtenerPortadaListaDeReproduccion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/manejador_de_archivos.Portadas/ObtenerPortadaListaDeReproduccion',
            protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
            protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
